using System.Runtime.Serialization;

namespace mCube.Service.Entites.MetaData
{
	[DataContract]
	public class Image
	{
		[DataMember]
		public string Id { get; set; } //Now generated by DB


		#region UnImportantPublicProperties
		[DataMember]
		public string Type { get; set; }
		[DataMember]
		public string Size { get; set; }
		[DataMember]
		public string Url { get; set; }
		[DataMember]
		public int Width { get; set; }
		[DataMember]
		public int Height { get; set; }

		#endregion
	}
}
