using System.ComponentModel.DataAnnotations;

namespace mCube.DataEntities.MetaData
{
    public class Image
    {
        [Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; } //Now generated by DB


        #region UnImportantPublicProperties

		public string TmdbId { get; set; }

        public string Type { get; set; }

        public string Size { get; set; }

        public string Url { get; set; }

        public int Width { get; set; }

        public int Height { get; set; }

        #endregion

    }
}
